version: '3'

services:

  web:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - php
      - db
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/app:rw
    links:
      - php

  php:
    build: ./php
    restart: always
    volumes:
      - ./app:/app:rw
      - ./private:/private:rw
    links:
      - db

  db:
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=application
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql

  drush:
    image: drupaldocker/drush:8
    working_dir: /app
    volumes:
      - ./app:/app:rw

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - '8081:80'
    links:
      - db
